# Generated by Django 3.0.8 on 2020-08-11 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200811_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='date',
        ),
    ]
