# Generated by Django 3.0.8 on 2020-08-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_remove_listing_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last updated'),
        ),
    ]
